# fly.toml app configuration file generated for agent-platform-log-shipper on 2025-12-19T17:15:35+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'agent-platform-log-shipper'
primary_region = 'nrt'

[build]
  image = 'flyio/log-shipper:latest'

[http_service]
  # fly-log-shipper(Vector API) 기본 포트
  internal_port = 8686
  force_https = true
  # 로그 수집은 항상 켜져 있어야 하므로 auto-stop 비활성화
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
